### ISSUE TITLE
Catalog - Workspaces RAW error evaluating group by

### ISSUE THREAD

**Issue by Gcsaniz** [RuiRomano/pbimonitor#18]
Large implementation (over 100k workspaces full scan, several days of 400+ modifications) using Azure blob storage is now failing on the group by:

Table.Group(#"Expanded Data.workspaces1", {"id"}, {{"AllRows", each _, type table [id=text, name=text, type=text, state=text, isOnDedicatedCapacity=logical, reports=list, dashboards=list, datasets=list, dataflows=list, ScanDate=nullable datetime]}}

![PbiMonitor Catalog - Workspaces RAW error](https://user-images.githubusercontent.com/16419745/177772277-ff3e2223-32ea-4c58-8fc9-70c454a466a7.png)
)

**Comment by RuiRomano** [comment]
On a large tenant, consider enabling the setting "PBIMONITOR_FullScanAfterDays" this will force a full scan every X days and the PowerQuery (last version of template) will only consider files since the last full scan.

You may need to force a full scan: https://github.com/RuiRomano/pbimonitor#force-a-full-scan

**Comment by CsanizAZ** [comment]
Doing a full scan every 7 days. This seems to have resolved the issue.

**Comment by NRREDDY999** [comment]
is it possible to push  to fix exceptions?
